# Generated by Django 2.1.1 on 2018-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sinopsis',
            field=models.TextField(),
        ),
    ]
