# Generated by Django 2.1.1 on 2018-09-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_portada',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sinopsis',
            field=models.CharField(max_length=364),
        ),
    ]
