# Generated by Django 2.1.1 on 2018-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180924_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
